# Generated by Django 4.1.13 on 2024-06-15 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comments',
        ),
        migrations.AddField(
            model_name='comment',
            name='post_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
