# Generated by Django 4.1.13 on 2024-12-22 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_post_is_reported'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_warned',
            field=models.BooleanField(default=False),
        ),
    ]
